server: 
  port: 8005
#  contextPath: /doctor

spring:
  application:
    name: doctor-zxy1
#    name: doctor
#  jpa:
#    generate-ddl: false
#    show-sql: true
  datasource:
    username: writer
    password: xjk123456!
    url: jdbc:mysql://172.30.0.217:3306/xjk?useUnicode=true&characterEncoding=utf-8
    
  redis:
    database: 0    # Redis数据库索引（默认错误的Unicode字符串!
    host: 172.30.0.219
    port: 6379
    password: 123456
#    expireTime: 100
#    pool:
#      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 8 # 连接池中的最大空闲连接
#      min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 0 # 连接超时时间（毫秒）
#    sentinel:
#      master: mymaster #name of Redis server  !
#      nodes: 10.117.130.210:26379,10.117.130.204:26379 #哨兵的配置列表
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
#  jackson:
#        time-zone: GMT+8
#        date-format: yyyy-MM-dd HH:mm


eureka:
  client:
    service-url:
      defaultZone: http://172.30.0.218:8000/eureka/
#    register-with-eureka: false
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30

swagger: 
  enable: true
constant:
  im:
    url: http://172.30.0.231:8092/tiguser/
    imOperUrl: http://172.30.0.231:8092/mucroom
    roomAdd: http://dialog/dialog/room/add
    givecardforfree: http://system/patient/orders/giveOrder
  fdfs:
    url: https://test.cis95132.com:8000/

im:
  server:
    roomUrl: http://172.30.0.231:8092/mucroom/add
    userAdd: http://172.30.0.231:8092/mucroom/join
    prefix: muc.114.113.117.243
url:
  patientUrl: http://patient/
  systemUrl: http://system/
  dialogUrl: http://dialog/
  gateWay: https://test.cis95132.com:8000/
  newhealthUrl: http://newhealth/
fdfs:
   soTimeout: 15000
   connectTimeout: 6000
   thumbImage:
       width: 150
       height: 150
   trackerList:
   - 172.30.0.218:22122

HEALTH_URL: https://h.95132.com/app/hospitals/nocontent/index1.html
EXHIBIT_URL: https://h.95132.com/app/hospitals/nocontent/index2.html
TYPICALILL_URL: https://h.95132.com/app/hospitals/nocontent/index3.html

#article 文章的h5路径前缀
article:
  url: https://test.cis95132.com:8000/group1/M00/00/BF/rB4A2lox7ieAKcdxAAAJVZlJsPY66.html
