# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: test
#  jpa:
#    generate-ddl: false
#    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xjk
    initialize: true
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
      host: smtp.exmail.qq.com
      username: 411075810@qq.com
      password:
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
logging:
  config: classpath:logback-spring.xml
#  path: /testRelease/sctipts/
#  file: /testRelease/sctipts/8020.log
#  file: /usr/cis/deploy_service/log/sctipts/8020.log
#  file: /usr/cis/deploy_service/log/sctipts/8020.log
#  file: /usr/cis/deploy_service/log/sctipts/8020.log



#eureka:
#  client:
#    service-url:
#      defaultZone: http://10.117.130.217:8761/eureka/
#       defaultZone: http://localhost:8761/eureka/ # ,http://peer2:8761/eureka/
#  instance:
#    prefer-ip-address: true
#---
#spring:
#  profile: user1
#server:
#    port: 8000
#---
#spring:
#     profile: user2
#server:
#     port: 8101
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yhyt.health.model
  
#SMS
constant:

    redis: 
       global: doctors
       patientGlobal: patient
       safekey: safekey
       salt1: yhyt
       salt2: yhyt
       
    sms:
       userId: j70336
       password: 563369
       address: http://61.135.198.131:8023/MWGate/wmgw.asmx
       pszSubPort: 10690329150503
       msg: 验证码：%s，有效期%s分钟!


   